### PR TITLE
Added several fake domain names from mytemp.email

### PR DESCRIPTION
**Pull request by jochembroekhoff**

### CODE REVIEW

**Comment by martenson** [comment]
hi @jochembroekhoff - thank you for the contribution but the domains are not matching the blacklist's format (please see this [issue](https://github.com/martenson/disposable-email-domains/issues/46) for details).

Are you willing to format them appropriately?

**Comment by jochembroekhoff** [comment]
Yes, I'll format them soon.

**Comment by MitsunChieh** [comment]
I just fix it on #69

**Comment by martenson** [comment]
resolved via #69

**Pull request closed without merging**
