### PR TITLE
Add lerbhe.com

### PR DESCRIPTION
**Pull request by philipto**
lerbhe.com is disposable according to https://fakecheck.email/lerbhe.com

### CODE REVIEW

**Comment by di** [comment]
Thanks for the contribution? Where can I generate a `@lerbhe.com` email address?

**Comment by philipto** [comment]
@di I did not come across specific service offering email addresses in this domain, however you can see the domain in various offerings regarding auto-generated accounts at hacker resources, where credentials are distributed, such as https://t.me/s/TeamBinnersOfficial. You can search for **lerbhe** there to have a proof.

**Comment by di** [comment]
Thanks! We generally prefer to be able to verify the domain, otherwise we can't actually determine whether this is a true disposable email domain or if it's someone's personal domain.

**Comment by tompec** [comment]
It comes from https://temp-mail.org/en/change
image

**Comment by di** [comment]
Thanks @tompec!

@philipto, can you also add:
* `openavz.com`
* `opwebw.com`
* `qmrbe.com`
* `rm2rf.com`
* `royandk.com`
* `tastrg.com`

**Comment by philipto** [comment]
@di Done. Please merge the PR or tell me how can I help and improve it further. Thank you!

**Comment by martenson** [comment]
Thank you both! 👍

**Pull request merged**
