### PR TITLE
Remove cock.li domains

### PR DESCRIPTION
**Pull request by lc-guy**
They are neither disposable nor temporary. All of the domains require a captcha at subscription as well.
Just because it's easy to sign up doesn't mean it's a "troll domain".

Most people using it actually like it because it's a no-bullshit, easy-to-use mail provider.

### CODE REVIEW

**Comment by vcanfield** [comment]
hi it looks like you beat me to this, but my commit also adds cock.li domains to the whitelist.

@lc-guy is there any way for you to add vcanfield/disposable-email-domains@b036198ccebbafb4cdc2e9c85f5854a07bf438f7 do this PR?

For more information, friends, cock.li is a super serious email provider used by super serious people. It gets flak because of its name but thousands of people use cock.li every day for legitimate purposes. I handle abuse reports very fast. I am a good boy, please remove my site thanks!!!!

**Comment by lc-guy** [comment]
done, @vcanfield

**Comment by martenson** [comment]
you got it

**Comment by vcanfield** [comment]
birds-with-arms-21
You're the man now dog!

**Pull request merged**
