### PR TITLE
Add domains from mailto.space to the blacklist

### PR DESCRIPTION
**Pull request by johnsudaar**
Service URL: https://mailto.space/

### CODE REVIEW

**Comment by deguif** [comment]
Could please also add `rdklcrv.xyz` domain, it comes from https://mailto.space/ too

**Comment by johnsudaar** [comment]
Done

**Comment by deguif** [comment]
Thanks @johnsudaar 

ping @martenson

**Comment by martenson** [comment]
Thanks a bunch @johnsudaar  & @deguif !

**Pull request merged**
