### PR TITLE
Update disposable_email_blocklist.conf

### PR DESCRIPTION
**Pull request by tuptuptuu**
add hey.com
DA0E22A7-460A-432A-8D9D-12AA53F8577B

The [iOS app](https://apps.apple.com/gb/app/hey-email/id1506603805) allows you to create free disposable email addresses.

### CODE REVIEW

**Comment by dhh** [comment]
This is a complete misnomer. HEY is a new email service with over 150,000 users and thousands of paying accounts. There is a separate service mandated by Apple that uses a specific 12 digit email address in the form of ####-####-#### that can be used for 14 days. You could create a similar address for a similar purpose on Gmail or any other service. These addresses are heavily limited and scrutinized to prevent abuse. Please dent this PR. You can find more information about HEY on https://hey.com. Thank you.

**Comment by dhh** [comment]
This user has been created solely for the harassment of HEY. See the rejection in other similar repos: https://github.com/ivolo/disposable-email-domains/pull/825

**Comment by tuptuptuu** [comment]
@dhh So how many of those 150000 addresses will still be working after 2 weeks? Presumably only the “thousands of paying accounts”.

> You could create a similar address for a similar purpose on Gmail or any other service. 

At least those addresses don’t expire. Gmail has very strong anti-abuse measures, from behavioural analysis to phone verifications. 

I had no trouble creating an expiring hey.com address using an OVH datacenter IP and a fake email address. You don’t even verify the secondary email you ask for.

> These addresses are heavily limited and scrutinized to prevent abuse.

Couls you explain exactly how this is supposed to work? You haven’t even bothered to add email or phone verification, are you just talking about ratelimiting?

> This user has been created solely for the harassment of HEY

Don’t you think this is a rather childish accusation? You offer disposable addresses on this domain, of course you’ll be added to DEA provider lists. 

There’s an easy solution available to you, just disable this feature until you can put these accounts under a different domain.

**Comment by bxio** [comment]
> > This user has been created solely for the harassment of HEY
> 
> Don’t you think this is a rather childish accusation? You offer disposable addresses on this domain, of course you’ll be added to DEA provider lists.

I just want to point out that you're the one hiding behind a throwaway github account, and you're calling other people childish. Seems to me it's the pot calling the kettle black.

Further, I get spam from email addresses from other large providers like Gmail and Outlook all the time, and yet the PR to add those domains to these lists oddly seem to be missing.

**Comment by tuptuptuu** [comment]
@bxio 
>I just want to point out that you're the one hiding behind a throwaway github account, and you're calling other people childish. Seems to me it's the pot calling the kettle black.

There's nothing childish about anonymity. @dhh clearly has no trouble with sending his 500k twitter followers to attack me because he doesn't like my PR, I clearly made the right call using a throwaway account for this.

>Further, I get spam from email addresses from other large providers like Gmail and Outlook all the time, and yet the PR to add those domains to these lists oddly seem to be missing.

It seems that you misunderstand the purpose of this list.

**Comment by di** [comment]
Thanks for the PR, but `hey.com` does not meet this repository's requirements for a disposable email domain.

Specifically, it does not exist for the sole purpose of creating disposable emails.

This would be roughly equivalent to adding `gmail.com` because users can create emails like `firstname.lastname+something@gmail.com`. It would have the effect of blocking all legitimate users of `hey.com`, even if they did not use the 14 day email feature.

**Pull request closed without merging**
