### PR TITLE
update(blocklist): include dropjar.com

### PR DESCRIPTION
**Pull request by alimagedayad**

### CODE REVIEW

**Comment by di** [comment]
Hi, thanks for the contribution. Can you show us how one would make a disposable email with `@dropjar.com` in it? The website seems to not resolve.

**Comment by alimagedayad** [comment]
Sure @di, You can make a disposable email with `@dropjar.com` in [getnada.com](https://getnada.com)

**Comment by alimagedayad** [comment]
fyi https://fakecheck.email/dropjar.com

**Comment by di** [comment]
Thanks! Can you also add `robot-mail.com`, it's the only other one that seems to be missing from that provider.

**Comment by alimagedayad** [comment]
@di Done!!

**Comment by alimagedayad** [comment]
Hi, can you enlist this repo on [hacktoberfest](https://hacktoberfest.digitalocean.com/hacktoberfest-update) for more contributions from hacktoberfest participants.

**Comment by di** [comment]
@alimagedayad I've added the `hacktoberfest-accepted` label instead. Thanks for the PR!

**Pull request merged**
