### PR TITLE
Update list with new entries

### PR DESCRIPTION
**Pull request by ar-anvd**

### CODE REVIEW

**Comment by deguif** [comment]
👍 LGTM to me, except the commit of merge which shouldn't appear on the commit list.

**Comment by ar-anvd** [comment]
> except the commit of merge which shouldn't appear on the commit list.

@deguif How can I fix it?

**Comment by deguif** [comment]
You should use `rebase` instead of `merge` when updating the branch of your fork.

**Comment by ar-anvd** [comment]
@deguif I would suggest you to create your own pull request with my changes, and ignore my PR. I don't know how to correct this. Sorry.

**Comment by martenson** [comment]
@ar-anvd We can rebase on merge (not that the commit history is of a huge importance in this repo, it is just nice to keep it clean), do not worry about it and thank you very much for the contribution.

**Pull request merged**
