### PR TITLE
Add new domains

### PR DESCRIPTION
**Pull request by egorsmkv**
New domains from this lists:

- https://raw.githubusercontent.com/ivolo/disposable-email-domains/89db50a73d7e29c83f0e78b0f2b4757b3f4cec8e/index.json
- https://raw.githubusercontent.com/andreis/disposable/6cceca83172b76c69337b52d9777bfaaf5aae580/domains.txt

### CODE REVIEW

**Comment by apollonin** [comment]
@martenson , hi! are you going to accept this PR?

**Comment by martenson** [comment]
@apollonin It has conflicts and it does not adhere to the standard of having no 3rd-and-below level domains. 

@egorsmkv I am sorry for not responding earlier. Are you planning to modify this PR according to what I state above?

**Comment by egorsmkv** [comment]
@apollonin I recommend you fork this project and add yourself new disposable domains. Perhaps, the author doesn't accept my pull request (see the PR's date).

**Comment by apollonin** [comment]
@egorsmkv author is here =) Please, improve your PR and it should be accepted.

**Comment by egorsmkv** [comment]
Okay, @martenson 

I close this issue and create new.

**Pull request closed without merging**
