### PR TITLE
Add new domains

### PR DESCRIPTION
**Pull request by igRo**
Numerous spam registrations were noticed on our service with emails on the following domains:
```
newmail.top
imailt.com
topmail2.net
topmail2.com
mail-now.top
one-mail.top
mailt.net
mailt.top
promailt.com
mailapp.top
```

### CODE REVIEW

**Comment by igRo** [comment]
8 new domains spotted:
```
email1.pro
imail1.net
mail-help.net
mail1.top
mail1web.org
mailhub.pro
max-mail.org
swift-mail.net
```

**Comment by igRo** [comment]
2 new domains added:
```
amail1.com
iiron.us
```

**Comment by di** [comment]
Hi, do you know which service(s) are using these domains?

**Comment by igRo** [comment]
I can't say for sure, but it seems most of these mailboxes were provided by https://temp-mail.org

There is one more domain listed on their site (`quick-mail.cc`), I think it's worth adding it to the stop list too

**Comment by di** [comment]
Thanks! It looks like that service uses just the following domains:

```
@amail1.com
@mail-help.net
@email1.pro
@mail1web.org
@mailhub.pro
@imail1.net
@max-mail.org
@quick-mail.cc
@mail1.top
@swift-mail.net
```

Can you update this PR to only include them? I'd be hesitant to add any that we can't find the source for.

**Comment by igRo** [comment]
Moved temp-mail.org domains to a separate PR: https://github.com/martenson/disposable-email-domains/pull/223

I will try to find a provider for the remaining domains within this PR.

**Comment by igRo** [comment]
Actually, all remaining domains (except for `iiron.us`?) were provided by the same service, here is a cached page:

https://web.archive.org/web/20191205125948/https://temp-mail.org/en/change

**Comment by di** [comment]
Got it, thanks for finding that! Let's drop `iiron.us` from this for now and I'll merge both PRs (or feel free to put them all back in this PR, your preference).

**Comment by igRo** [comment]
Let's close this PR and merge #223 - it has a cleaner git history. I added the remaining domains except for the `iiron.us` there.

**Pull request closed without merging**
