### PR TITLE
adding getnada.com

### PR DESCRIPTION
**Pull request by ereli**
image

### CODE REVIEW

**Comment by martenson** [comment]
thanks @ereli !

**Comment by szepeviktor** [comment]
@marcelstoer It is really
```
@amail.club
@cmail.club
@wmail.club
@duck2.club
@cars2.club
@banit.club
@banit.me
@nada.ltd
@nada.email
@getnada.com
```

**Comment by martenson** [comment]
@szepeviktor Are you willing to open a PR fro those?

**Comment by szepeviktor** [comment]
No. Sorry.

You only have to go to getnada.com and click `Add more` - then you see the dropdown.

**Comment by martenson** [comment]
@szepeviktor added via 41bba396e52f16296bf346b29a34145f6c415aac - thanks

**Pull request merged**
