### PR TITLE
Add cheerful.com to list

### PR DESCRIPTION
**Pull request by radzhome**

### CODE REVIEW

**Comment by szepeviktor** [comment]
I think the list is sorted.

**Comment by martenson** [comment]
@radzhome what is the source of this domain being disposable?

Also @szepeviktor is right, the list is in alphabetical order. If you provide explanation for the addition I will fix it.

**Comment by szepeviktor** [comment]
I think it is a 1&1 ( the biggest German provider) domain

```
$ host cheerful.com
cheerful.com has address 141.8.224.143
cheerful.com mail is handled by 10 mx00.mail.com.
cheerful.com mail is handled by 10 mx01.mail.com.
```

**Comment by szepeviktor** [comment]
c

**Comment by martenson** [comment]
@szepeviktor nice find, thanks

**Comment by szepeviktor** [comment]
@martenson You may close this one.

**Pull request closed without merging**
