### PR TITLE
Add two additional garbage email domains

### PR DESCRIPTION
**Pull request by Soulou**

### CODE REVIEW

**Comment by martenson** [comment]
@Soulou Could you please provide sources for a claim these domains have disposable email providers? Thank you.

**Comment by Soulou** [comment]
What kind of sources do you need?

**Comment by martenson** [comment]
@Soulou What leads you to think these are disposable email domains?

**Comment by deguif** [comment]
`emailsecurer.com` is coming from https://mailto.space/
The whois also show it was registered by https://fullstack.at/ the same that are hosting https://mailto.space/

**Comment by martenson** [comment]
Thanks @deguif and @Soulou - lgtm.

**Pull request merged**
